name: Auto Approve Pull Request
on: 
  issue_comment:
    types: [created]

jobs:
  auto-approve:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#Approved') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Approve Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr review ${{ github.event.issue.number }} --approve -R ${{ github.repository }}
